### ISSUE TITLE
Timeline ist offen geblieben

### ISSUE THREAD

**Issue by rabeKneo** [The-Liso-Project/RolePlay#112]
**Beschreibe den Bug**
Timeline blieb dauerhaft offen und hat sich nicht gefüllt
konnte später nicht reproduziert werden

**Erwartetes Verhalten**
Timeline sollte sich füllen bzw nicht doppelt aufgehen

**Weitere Informationen**
Nur beim Frosch sammeln

**Comment by SaimenHD** [comment]
Bei sehr häufigen und längeren Farmen passiert der Bug

**Comment by rabeKneo** [comment]
konnte nicht nachgestellt werden
