### ISSUE TITLE
IC Report funktion

### ISSUE THREAD

**Issue by rabeKneo** [The-Liso-Project/RolePlay#152]
**Wie bist du auf dieses Feature gekommen?**
Es gibt noch keine Möglichkeit einen Spieler zu reporten

**Wie stellst du dir dieses Feature vor**
eine IC Liste mit durchnummerierten spielern, nummerierung ist für jeden anders
Reports können von jedem Admin mit uhrzeit eingesehen werden

**Comment by Damunnator** [comment]
einen Chat in dem man gegebenenfalls mit einem Supporter schreiben kann

**Comment by rabeKneo** [comment]
Den Chat kann man einbauen allerdings sehe ich das als eigene Funktion
Das funktioniert auch nur wenn zum Zeitpunkt des Report erstellens ein Supporter verfügbar ist und den Fall angeht
