### ISSUE TITLE
Fraktiongarage auf der Map sichtbar

### ISSUE THREAD

**Issue by Yummicooki** [The-Liso-Project/RolePlay#155]
**Beschreibe den Bug**
Hallo beim Erstellen von Fraktionsgaragen Polizei ist es mir aufgefallen, dass die Symbole für mich auch sichtbar sind, wenn ich nihct im Dienst bin. Also wie bei einem normalen Spieler sichtbar.

**Erwartetes Verhalten**
Es wird erwartet, dass die symbole auf der Karte nicht für alle sichtbar sind.

**Screenshots**
![grafik](https://github.com/The-Liso-Project/RolePlay/assets/134153212/2ade13f5-f6cb-430b-b808-15320a3fe725)

**Comment by rabeKneo** [comment]
Fraktionsgaragen sollten generell nicht sichtbar sein
Liegt anscheinend an der änderung des Fraktionstyps, dort wird der Blip nicht richtig entfernt
