### ISSUE TITLE
Kleidungsänderung setzt torso auf standard zurück

### ISSUE THREAD

**Issue by rabeKneo** [The-Liso-Project/RolePlay#156]
**Beschreibe den Bug**
Mit jeder Änderung eines Kleidungsstückes ändert sich der torso auf den selben immer wieder zurück

**Comment by XeniaGX** [comment]
Nach jemdem joinen auf den Server geschieht das auch. 
![neu einloggen](https://github.com/The-Liso-Project/RolePlay/assets/134194500/baee6052-0cd3-4d2b-b5ac-e079cf11b4f7)
