### ISSUE TITLE
Einzelne Items verkaufen ohne Verarbeitung

### ISSUE THREAD

**Issue by XeniaGX** [The-Liso-Project/RolePlay#159]
Die einzelnen "Zutaten" die man auf der Map sammeln kann, könnte man auch verkaufen. Wenn man die einzelnen "Zutaten" wie Trauben, Zuckerrohr o.ä. zu viel gesammelt hat oder ggf. falsch, könnte man sie doch seperat verkaufen. Einen Ort dafür könnte ich mir gut am Pier wo das Riesenrad steht gut vorstellen, da dort "Verkaufsstände" schon vorhanden sind. 
Die Preise kann man festlegen oder auch je nach Tageszeit und/oder Wochentag variiren lassen. 

![Screenshot_7](https://github.com/The-Liso-Project/RolePlay/assets/134194500/5ef539b6-4dd1-44f4-8d8f-2941f24b4afa)
![Stände](https://github.com/The-Liso-Project/RolePlay/assets/134194500/e276d40f-9507-4108-be3e-1c5fd1a07c0b)

**Comment by rabeKneo** [comment]
ist eingefügt allerdings ist die Position jetzt am Hafen.
