### ISSUE TITLE
Gesichtssynch.

### ISSUE THREAD

**Issue by Yummicooki** [The-Liso-Project/RolePlay#163]
**Beschreibe den Bug**
Weibliches Gesicht wird bei anderen Usern als männlich erkannt.

**Erwartetes Verhalten**
Gleiches Gesichtsbild

**Screenshots**
![grafik](https://github.com/The-Liso-Project/RolePlay/assets/134153212/e8252f19-74b2-401a-b26c-68d2a67d9634)
![grafik](https://github.com/The-Liso-Project/RolePlay/assets/134153212/9935e232-8446-4859-a9c2-a108b0d1253c)

**Comment by rabeKneo** [comment]
Den Sync können wir nur schwer beeinflussen, zumindest hat jeder versuch das zu beeinflussen zu großen lags und keiner verbesserung geführt.

Wir müssen abwarten bis AltV den Sync dafür integriert hat.

**Comment by rabeKneo** [comment]
Anscheinend werden auch die eltern nicht synchronisiert

**Comment by SaimenHD** [comment]
Sync in Version 1.0 umgesetzt
