### ISSUE TITLE
Spieler durchsuchen

### ISSUE THREAD

**Issue by Yummicooki** [The-Liso-Project/RolePlay#164]
**Beschreibe den Bug**
Funktion E geht nicht 

**Erwartetes Verhalten**
Inventar sollte sich öffnen, allerdings ist nichts zu sehen.

**Comment by rabeKneo** [comment]
E-Funktion wurde auf dem Dev Server behoben.

- [x] 1. Es kann allerdings das menü geöffnet werden und dann weggelaufen werden, ein wegnehmen von Items ist immer noch möglich

- [x] 2. Wenn ein Spieler beim ergeben geschlagen wird oder bewusstlos wird, kann dieser sich danach normal bewegen und trotzdem weiter dursucht werden

**Comment by rabeKneo** [comment]
wenn man nun das menü öffnet und weggeht kann man ab einer bestimmten entfernung kein Item mehr aus dem Inventra nehemn
Wenn sich ein spieler ergibt und danach schaden bekommt, geht der Charakter nun automatisch in die ergeben haltung zurück.
Wenn der spieler beim ergeben stirbt, wird das ergeben abgebrochen, das durchsuchen funktioniert bis zum wiederbeleben
Man kann auch durchsucht werden wenn man bewusstlos ist.
Die ergeben animation wurde ausgetauscht
