### ISSUE TITLE
Kleidungsladen lädt sehr lange

### ISSUE THREAD

**Issue by rabeKneo** [The-Liso-Project/RolePlay#186]
**Beschreibe den Bug**
Die Kleidungsladen HTML braucht mehrere Minuten bis alles dargestellt wird

**Erwartetes Verhalten**
Die HTML hat es mal in weniger als 1 Sekunde angezeigt

**Comment by rabeKneo** [comment]
Ladezeit lässt sich nicht weiter beschleunigen, braucht nur noch wenige Sekunden

Halsschmuck lädt allerdings nicht
Wenn man auf Halsschmuck umschaltet, kann man danach nicht auf T-Shirt umschalten.
Man muss erst auf Oberteil / Hose / Schuhe und dann wieder auf T-Shirt gehen



![Image](https://github.com/The-Liso-Project/RolePlay/assets/70174901/e00e1db3-fb23-4680-a3a9-51a527fc0171)

**Comment by SaimenHD** [comment]
Bug behoben
