### ISSUE TITLE
HUD anzeige

### ISSUE THREAD

**Issue by BlackNight950** [The-Liso-Project/RolePlay#194]
**Beschreibe den Bug**
- Essens Kreis anzeige das weiße muss entfernt werden.
- Voice Range kreis das Symbol muss heller gemacht werden. 

**Screenshots**

![Image](https://github.com/The-Liso-Project/RolePlay/assets/77077378/2fd05ef7-e7c9-44e8-b7f0-00819ff2a69d)

**Comment by SaimenHD** [comment]
Symbole müsse für Andere Bildschirmauflösung angepasst werden
