### ISSUE TITLE
Character Creator alle sachen einfügen

### ISSUE THREAD

**Issue by BlackNight950** [The-Liso-Project/RolePlay#200]

**Comment by BlackNight950** [comment]
Ich würd gerne noch alles Sachen einfügen die man beim char erstellen auswählen kann da nicht jedes Detail vorhanden ist, (z.b. es gibt nicht genügend Auswahl für das weibliche Geschlecht genau so für männlichen char)

**Comment by rabeKneo** [comment]
Kleidungen kommen nicht in den Char Creator. die kann sich jeder im Kleidungsladen kaufen.
