### ISSUE TITLE
Char creator Charakter drehen

### ISSUE THREAD

**Issue by SaimenHD** [The-Liso-Project/RolePlay#205]
**Beschreibe den Bug**
Der Charakter kann noch nicht gedreht werden 

**Erwartetes Verhalten**
Mit dem mittleren Balken soll sich der Charakter drehen lassen!

**Weitere Informationen**
Kann mit Facesync zusammen eingebaut werden wenn möglich eventuell auch Umbau des charcreators

**Comment by SaimenHD** [comment]
Wollen wir den Player in der Charaktererstellung Freezen?

**Comment by rabeKneo** [comment]
der Charakter ist schon gefreezed, das stoppt aber die Animationen nicht.
Drehung funktioniert jetzt aber

**Comment by SaimenHD** [comment]
Rotation mit zum Server geben damit der Player in der richtigen rotation neu gespawnt wird oder die Rotation clientsidig immer setzen wenn ein wert geändert wird.
