### ISSUE TITLE
Gesetzbuch vorbereiten

### ISSUE THREAD

**Issue by BlackNight950** [The-Liso-Project/RolePlay#222]
Rabe und Saimen

**Comment by SaimenHD** [comment]
Variante 2. Polizeigesetz und Variante 3. 4 Zivilrecht, 7 Medizinrecht, 8 Immobilienrecht, mit Variante 1 vergleichen und darin ergänzen

**Comment by rabeKneo** [comment]
Gesetzbücher sind alle geschrieben
