### ISSUE TITLE
Manche kleidung wird nicht gesynced

### ISSUE THREAD

**Issue by SaimenHD** [The-Liso-Project/RolePlay#23]

**Comment by rabeKneo** [comment]
siehe https://docs.altv.mp/gta/articles/ped/clothing.html
und https://discord.com/channels/371265202378899476/543835094515974154/904357238515331134
und https://discord.com/channels/371265202378899476/547079158300147725/916414430894522439

wir müssen eine eigene überstzung von component id in dlc name und id schreiben

**Comment by rabeKneo** [comment]
gab inzwischen Updates muss noch mal geprüft werden

**Comment by rabeKneo** [comment]
Vermutlich durch altv update behoben
