### ISSUE TITLE
Fahrzeug Kopieren

### ISSUE THREAD

**Issue by HeshyHD** [The-Liso-Project/RolePlay#231]
**Fahrzeug Kopiert**
Wenn Mann ein Fahrzeug tuned, spawn das Fahrzeug neu aber nur bei diversen Optionen

**Erwartetes Verhalten**
Bitte erkläre das Erwartete Verhalten, sofern das nicht aus der Bugbeschreibung hervorgeht

**Comment by rabeKneo** [comment]
Lässt sich bei mir in der Testumgebung gerade nicht nachstellen.
Ich habe aber auch noch nicht alle Varianten getestet.

**Comment by rabeKneo** [comment]
tritt nur bei folgenden optionen auf:
- rechter radkasten
- linker radkasten
- xenon
- fenstertönung
- interior farbe
- primärfarbe
- sekundärfarbe
- pearlfarbe
- design
- scheinweferfarbe

**Comment by rabeKneo** [comment]
Sobald eine dieser Optionen angewendet wird (z.B. die aktuelle Primärfarbe ein mal anwenden), dupliziert sich das auto nicht mehr.

**Comment by rabeKneo** [comment]
Neon deaktivieren als erste Tuning Option reicht auch aus. währe ein Workaround.

**Comment by rabeKneo** [comment]
Bug scheint jetzt behoben.
