### ISSUE TITLE
augenbrauen hinzufügen

### ISSUE THREAD

**Issue by SaimenHD** [The-Liso-Project/RolePlay#64]
OverlayID ist die 2 Index wahrscheinlich einfach die Augenbrauenform hochgezählt 

https://docs.altv.mp/gta/articles/ped/appearance.html?q=eyebrow#

https://gta.fandom.com/wiki/Barbers/GTA_Online#Eyebrows

**Comment by rabeKneo** [comment]
Die Augenbrauen sind nur clientseitig in der HTML auskommentiert gewesen, tests notwendig

**Comment by rabeKneo** [comment]
Augenbrauen typ ändern funktioniert nicht, augenbrauen können aber aktiviert werden
