### ISSUE TITLE
sporadische lags auf QA Server

### ISSUE THREAD

**Issue by SaimenHD** [The-Liso-Project/RolePlay#67]

**Comment by rabeKneo** [comment]
auffällig ist aber dass diese Lags genau im Hauptgebiet des Tunnelnetzwerks der U-Bahn Liegen
hier mal eine sehr sehr Skizzenhafte Zeichnung der U-Bahn Tunnel und des Lag Gebietes welches wir bisher kennen

Legende:
***Blau:***
     - sind bewiesene Straßen in denen Lags unter bestimmten derzeit noch unbekannten bedingungen auftreten können
***Rot:***
    - ist der Bereich in dem wir das Problem vermuten und 2 Markante Punkte die höchstwahrscheinlich nichts mit den Lags zu tun haben
***Gelb***
    - ist der geschätzte Verlauf der U-Bahn und der Tunnel in dem Bereich

In dem Roten Bereich befinden sich 2-3 MLO

Eine Abhängigkeit zur Hardware kann nicht hergestellt werden, die Lags wurden auf mindestens 4 Computern mit komplett unterschiedlicher Hardware getestet, darunter ist auch mindestens 1 schwacher und 2 Leistungsstarke Computer

![Image](https://user-images.githubusercontent.com/70174901/187540386-4e7c8ae0-f171-4a31-9f48-6f82f9a83e28.png)

**Comment by rabeKneo** [comment]
Solange es den Spielbetrieb nicht stark beeinträchtigt würde ich die Fehlersuche verschieben bis mehr beweise und mehr betroffene sich melden.

Wir sind für alle Hinweise und Tests offen

**Comment by rabeKneo** [comment]
Fehler konnte inzwischen gefunden werden
Es lag an einigen maps die sich gegenseitig behindert haben und somit die lags ausgelöst haben
Alle betroffenen Maps werden nicht mehr verwendet
