### ISSUE TITLE
Verarbeitungsleiste verschwindet nicht

### ISSUE THREAD

**Issue by SaimenHD** [The-Liso-Project/RolePlay#72]

**Comment by SaimenHD** [comment]
Beim Bearbeiten von Materialien verschwindet laut Aussage die Timeline nicht

**Comment by rabeKneo** [comment]
HJabs gerade auf dem Dev Server getestet und die Leiste ist beim verarbeiten immer wie erwartet verschwunden

**Comment by SaimenHD** [comment]
Mit Zucker getestet und auch nicht den Fehler gehabt

**Comment by SaimenHD** [comment]
fehler ist bei zu e Spam aufgetreten

**Comment by rabeKneo** [comment]
Massiver Spam (Makro) oder langer manueller Spam nötig
