### ISSUE TITLE
Fraktionskonto

### ISSUE THREAD

**Issue by rabeKneo** [The-Liso-Project/RolePlay#74]

**Comment by rabeKneo** [comment]
Fraktioinskonten werden bereits erzeugt.
Es gibt aber noch keinen Möglichkeit auf diese Konten zuzugreifen

**Comment by rabeKneo** [comment]
Anpassung der HTML ist notwendig um Zugriff auf das Konto zu geben.
Es wird ein neuer Button in die HTML eingefügt.
Dieser zeigt das Fraktionskonto an, den button sieht nur der Chief einer Fraktions

**Comment by SaimenHD** [comment]
bank/index.js ifid is not defined auf Zeile 24
