### ISSUE TITLE
Beim Tanken erst nach Tanken Bezahlauswahl

### ISSUE THREAD

**Issue by rabeKneo** [The-Liso-Project/RolePlay#78]

**Comment by SaimenHD** [comment]
Bezahl Auswahl kommt direkt nach Tankart Auswahl während getankt wird. Man kann während des Tankvorganges nicht losfahren/abbrechen

**Comment by rabeKneo** [comment]
Ist nur ein schönheitsfehler, würde ich in Version 2 Weiter bearbeiten

**Comment by rabeKneo** [comment]
aufgrund von anderen Bugs wurde die Änderung doch schon in Version 1 umgesetzt
