### ISSUE TITLE
Kleidungsladen HTML

### ISSUE THREAD

**Issue by rabeKneo** [The-Liso-Project/RolePlay#85]
- [x] Dynamisches Erstellen der Artikel
- [x] Textur Buttons
- [x] Show Funktion
- [x] Buy Funktion
- [x] Artikelsuche
- [x] Dynamische Anpassen der Bezeichnungen
- [x] Markierung des ausgewählten artikels (angezogen angeklickt)

**Comment by SaimenHD** [comment]
Bezeichnungen dürfen maximal 31 Zeichen lang sein

**Comment by rabeKneo** [comment]
Wenn länge der Zeichen angepasst wurde kann funktion dynamische anpassen der Bezeichnungen getestet werden
