### ISSUE TITLE
Map Fehler in Sandy Shores

### ISSUE THREAD

**Issue by rabeKneo** [The-Liso-Project/RolePlay#89]
**Beschreibe den Bug**
Die Map lädt unvermittelt neu wenn man an dem gebäude vorbei fährt
Einige gebäude fehlen hinter dem unsichtbaren haus

**Screenshots**
Map Position:
![image](https://user-images.githubusercontent.com/70174901/187289295-b2a44052-5605-4cb4-85be-a679c2dd25cf.png)
Mit Bug:
![image](https://user-images.githubusercontent.com/70174901/187289335-4da24713-3666-4e8a-84b8-a77e226d048e.png)
Ohne Bug:
![image](https://user-images.githubusercontent.com/70174901/187289362-082aa705-a96c-48cc-8c29-698dd3e1c4e5.png)

**Weitere Informationen**
Bei mir aufgetreten als ich rechts am Haus vorbei gefahren bin

**Comment by rabeKneo** [comment]
Das unsichtbare haus neben dem ich stehe hat auch kollision

**Comment by HeshyHD** [comment]
ist behoben worden getestet von rabe und john
